apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-srv
  annotations: 
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/use-regex: "true"                # Name of the Ingress resource
    nginx.ingress.kubernetes.io/proxy-connect-timeout: "1800"  # 30 minutes
    nginx.ingress.kubernetes.io/proxy-send-timeout: "1800"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "1800"
    nginx.ingress.kubernetes.io/proxy-next-upstream: "error timeout http_502 http_503 http_504"
    nginx.ingress.kubernetes.io/proxy-body-size: "50m"
spec:
  ingressClassName: nginx            # Specifies the Ingress controller to use (nginx in this case)
  tls:
    - hosts:
        - tickets.dev
      secretName: tickets-dev-tls
  rules:                             # List of routing rules
    - host: tickets.dev                # Domain name that this rule applies to
      http:                          # HTTP routing configuration
        paths:                       # List of paths under the given host
          - path: /api/auth/?(.*)             # URL path to match
            pathType: ImplementationSpecific        # Match all paths that start with "/posts"
            backend:                 # Defines where traffic should be sent
              service:               # Backend is a Kubernetes Service
                name: auth-srv  # Name of the Service to route traffic to
                port:
                  number: 4000       # Port on the Service to forward requests
          - path: /api/tickets/?(.*)
            pathType: ImplementationSpecific
            backend:
              service: 
                name: tickets-srv
                port: 
                  number: 4000
          - path: /?(.*)
            pathType: ImplementationSpecific
            backend:
              service: 
                name: client-srv
                port: 
                  number: 3000
